### ISSUE TITLE
Those ugly avatars on homepage :(

### ISSUE THREAD

**Issue by abombus3** [the-omnipotent/YouTubeRedux#301]
Since the new update came out, avatars on the homepage are visible, and that looks ugly. Tried to change that with settings but nothing, so I assume that's the bug of the new update

<img width="479" height="219" alt="Image" src="https://github.com/user-attachments/assets/e11efb2d-e9a9-4604-843c-8640d828b751" />

<img width="480" height="205" alt="Image" src="https://github.com/user-attachments/assets/11d384c2-cc5a-473e-b4a6-0ef64fcaf2ea" />

**Comment by omnidevZero** [comment]
Resolved in v3.9.3 which is pending review for Chrome at the moment.

**Comment by abombus3** [comment]
I fear the issue is still here for me...

<img width="474" height="196" alt="Image" src="https://github.com/user-attachments/assets/e2567a88-aa33-4903-a33f-568482c9d2c3" />

<img width="479" height="212" alt="Image" src="https://github.com/user-attachments/assets/3e88a0f8-ab3f-487c-859b-491af458bc2c" />

although the extension has been updated

<img width="264" height="60" alt="Image" src="https://github.com/user-attachments/assets/37dc7261-f1e8-447e-a7e1-4efaba0f64d1" />

**Comment by omnidevZero** [comment]
<img width="579" height="459" alt="Image" src="https://github.com/user-attachments/assets/5899c98a-05c9-47e9-8b16-3b99954a9e99" />

Do you have this setting enabled?

**Comment by abombus3** [comment]
Yes, thank you! 

the problem solved!!

**Comment by rg3017** [comment]
Homepage avatars have come back for me, even with the setting enabled. Also, are the titles of videos on the homepage bigger than normal for anyone else? It used to only be on the homepage, but it's infected my subscriptions page now as well.

<img width="310" height="289" alt="Image" src="https://github.com/user-attachments/assets/41dccf45-3b49-4d28-8240-66b19342fbf4" />

**Comment by Schnauzer-World** [comment]
Yeah, back for me too. I wish they would just leave the interface alone.

**Comment by omnidevZero** [comment]
A bit late but fix incoming!

**Comment by Schnauzer-World** [comment]
Thanks, looks much better now.
